In [1]:
import numpy as np

# Create Array

In [3]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
print np.array(l1)
print np.array([l1,l2])

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


## arithmatic

In [5]:
a = np.arange(6).reshape(2,3)
print a
print a * a # element-wise operation
print np.dot(a,a.T) # linear operation

[[0 1 2]
 [3 4 5]]
[[ 0  1  4]
 [ 9 16 25]]
[[ 5 14]
 [14 50]]


## slices

In [6]:
A = np.arange(20)
a = A[:10]       # pass the pointer 
print 'A = ', A
a[:] = 100     # value is changed on original variable too, this is different from list
print 'A = ', A

A =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
A =  [100 100 100 100 100 100 100 100 100 100  10  11  12  13  14  15  16  17
  18  19]


In [9]:
B = np.copy(A)
B[:10] = 1
print 'A = ', A

A =  [100 100 100 100 100 100 100 100 100 100  10  11  12  13  14  15  16  17
  18  19]


In [13]:
a = np.arange(25).reshape(5,5)
print a[1][3]
print a[:2,1:4]
print a[[2,3]]   # rows

8
[[1 2 3]
 [6 7 8]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


## Functions

In [17]:
x = np.array( [1,2,3] )
y = np.array( [4,5,3] )

np.add(x,y), np.maximum(x,y), np.minimum(x,y), np.equal(x,y), np.all(np.equal(x,y)), np.any(np.equal(x,y))

(array([5, 7, 6]),
 array([4, 5, 3]),
 array([1, 2, 3]),
 array([False, False,  True], dtype=bool),
 False,
 True)

http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs