In [4]:
import numpy as np

In [6]:
a = np.arange(10)
a ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
%timeit [x for x in a if x%2==0]

The slowest run took 4.61 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.67 µs per loop


In [11]:
%timeit filter(lambda x: x%2 == 0, a)

The slowest run took 4.05 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.42 µs per loop


In [12]:
%timeit a[a%2==0]

The slowest run took 11.78 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.21 µs per loop


In [13]:
a.dtype

dtype('int64')

In [14]:
np.array([True,0,2], dtype="bool_")

array([ True, False,  True], dtype=bool)

In [22]:
np.random.shuffle(a)
print a
a.argmax()

[3 7 1 0 8 2 5 6 9 4]


8

In [24]:
print a.mean(), a.std()

4.5 2.87228132327


In [25]:
np.linspace(1,2,5)

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [26]:
np.linspace(1,10,11).astype('int')

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
ar = np.random.randint(1,51,20)
ar

array([39, 49, 45, 13,  6,  5, 12, 12, 34, 41, 45,  1, 38, 24, 36, 48, 19,
       21, 47, 46])

## vectorization

In [44]:
def new_func(num):
    if num < 30:
        return 30
    else:
        return num

In [40]:
new_func(ar)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [45]:
vnew_func = np.vectorize(new_func)

In [46]:
vnew_func(ar)

array([39, 49, 45, 30, 30, 30, 30, 30, 34, 41, 45, 30, 38, 30, 36, 48, 30,
       30, 47, 46])

### matrics

In [47]:
ar.reshape(4,5)

array([[39, 49, 45, 13,  6],
       [ 5, 12, 12, 34, 41],
       [45,  1, 38, 24, 36],
       [48, 19, 21, 47, 46]])

In [49]:
ar2 = np.zeros((5,5,5))

In [50]:
ar2.ndim

3

In [62]:
np.random.seed(10)
ar1 = np.random.randint(1,10,4).reshape(2,2)
ar2 = np.random.randint(1,10,4).reshape(2,2)
ar1>ar2

array([[ True, False],
       [ True, False]], dtype=bool)

In [54]:
(ar1>ar2).sum()

2

In [55]:
(ar1>ar2).sum(axis=0)

array([2, 0])

In [56]:
ar1.transpose()

array([[5, 2],
       [1, 1]])

In [57]:
ar1.T

array([[5, 2],
       [1, 1]])

In [58]:
ar1.T*ar1  # ELement-wise Operation !!!!!!

array([[25,  2],
       [ 2,  1]])

In [60]:
ar1.flatten()

array([5, 1, 2, 1])

In [63]:
np.vstack((ar1,ar2)) # vertical

array([[5, 1],
       [2, 1],
       [2, 9],
       [1, 9]])

In [65]:
np.hstack((ar1,ar2)) # horizontal

array([[5, 1, 2, 9],
       [2, 1, 1, 9]])

In [66]:
np.concatenate((ar1,ar2),axis=1)

array([[5, 1, 2, 9],
       [2, 1, 1, 9]])

In [67]:
np.dstack((ar1,ar2))  # add dimension !!

array([[[5, 2],
        [1, 9]],

       [[2, 1],
        [1, 9]]])

In [69]:
ar1

array([[5, 1],
       [2, 1]])

In [68]:
np.hsplit(ar1,2)

[array([[5],
        [2]]), array([[1],
        [1]])]

In [70]:
np.vsplit(ar1,2)

[array([[5, 1]]), array([[2, 1]])]